# Generated by Django 4.2.7 on 2025-06-12 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("punch_in", models.DateTimeField(blank=True, null=True)),
                ("punch_out", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "break_duration",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "working_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_late_in", models.BooleanField(default=False)),
                ("is_early_out", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("in_progress", "In Progress"),
                            ("on_break", "On Break"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__name"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("punch_in", "Punch In"),
                            ("punch_out", "Punch Out"),
                            ("break_start", "Break Start"),
                            ("break_end", "Break End"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("is_late", models.BooleanField(default=False)),
                ("is_early", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PunchCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("punch_in", models.DateTimeField()),
                ("punch_out", models.DateTimeField(blank=True, null=True)),
                ("is_late_in", models.BooleanField(default=False)),
                ("is_early_out", models.BooleanField(default=False)),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_cycles",
                        to="timetracking.worksession",
                    ),
                ),
            ],
            options={
                "ordering": ["punch_in"],
            },
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(
                fields=["employee", "date"], name="timetrackin_employe_9f32e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(fields=["date"], name="timetrackin_date_80a60d_idx"),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(fields=["status"], name="timetrackin_status_917c7f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="worksession",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["employee", "timestamp"], name="timetrackin_employe_2dfbed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["type", "timestamp"], name="timetrackin_type_6fb9c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["timestamp"], name="timetrackin_timesta_072035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="punchcycle",
            index=models.Index(
                fields=["work_session", "punch_in"],
                name="timetrackin_work_se_eec3cb_idx",
            ),
        ),
    ]
