# Generated by Django 4.2.7 on 2025-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
